#!/bin/bash

# Define valid commands
valid_commands=("configure_default" "down" "up" "get_gateway" "ip_offset" "params" "print_params" "wait_for_device")

# Check if the command provided is in the valid commands list
if [[ " ${valid_commands[@]} " =~ " $1 " ]]; then
    # Execute the command by calling the respective binary and forwarding all other arguments

    if [[ "$1" == "params" ]]; then
        source /bin/novpn_utils/nu_"$1".sh "${@:2}"
    else
        /bin/novpn_utils/nu_"$1".sh "${@:2}"
    fi
else
    echo "Error: Unknown command '$1'. Valid commands are: ${valid_commands[*]}"
    exit 1
fi
